nvfl:
  folderpath: "nvfl/jobs/nvfl"
  networkfile: "network.py"
  udffile: "udf.py"
  data_subfolder: "data"

simulation:
  job_folder: "nvfl/jobs/nvfl"
  workspace: "workspace"
  n_clients: 2
  clients: "f,s"
  threads: 1
  gpu: "3"
  max_clients: 100

train:
  lr: 0.01
  epochs: 10
  loss_fn: "CrossEntropyLoss"
  batch_size: 1

pt_constants:
  servername: "server"
  filenmodelname: "FL_global_model.pt"
  localmodelname: "local_model.pt"
  modelsdir: "models"